project:
  type: book  
  output-dir: docs

book:
  title: "Too Hot to Handle: An Evaluation of Water Temperature at the Dauphin Island Nuclear Power Plant"
  author: "Dominic Sander"
  page-footer:
    left: "Copyright 2025, Dominic Sander"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - references.qmd
  appendices:
    - r-packages-used.qmd
    - draft-data-doc.qmd
    - draft-exec-summary.qmd
    - draft-results.qmd
    - draft-intro-conclusions.qmd

bibliography: references.bib

execute:
    error: true
    message: false
    warning: false

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



