# Discussion

In order to answer the questions of interest posed in the introduction, the data collected above must be properly analyzed. The reactor at Dauphin Island is designed to use sea water during the cooling process. To do so, it collects sea water to pump through the reactor in order to transfer energy away from the reactor and into the water, warming it. Warmer water cannot have as much thermal energy transferred into it as cooler water, and therefore cannot generate as much power [@Cooling2020]. It is also important to note that there are environmental factors to be considered. A power plant releasing heated water back into its surroundings can disrupt the ecological balance, harming or killing the plants and animals in the area. Due to the potential risks and NRC regulations, once the water temperature surrounding the plant reaches 85°F, the plant must reduce all operations to 50% for the next 24 hours.

According to the U.S. Energy Information Administration, 33% of the electricity used in Alabama in 2023 was generated by the two nuclear power plants in the state [@EIA]. Just one of the two operating at half capacity would have a detrimental affect on consumer energy use in the state. Residents would have to operate without certainty of when they would have power, fearful of outages and relying on generators during the summer months. Essential businesses such as hospitals, grocery stores, and pharmacies will take precedent, likely not losing power completely, but possibly having to cut down on electrical usage.

## Limitations
Throughout the data collection process, we did our best to reduce any potential error. Despite using more than a decade of data collected by the NOAA, finding more data that goes back even further would be helpful in making our results more accurate. We may not get a complete picture of trends in water temperature, so we may not be able to make predictions about the future as accurately. In the data we collected, every day of each year has multiple observations throughout the day, so we do not have to worry about only observing a maximum or minimum temperature for that day. It is also important to note that we combined a few data sets to create our final combined set. All but one year of data came from the Dauphin Island 1 and 2 meteorological stations, which are conveniently located less than a mile away from each other. This difference would likely be negligible and can be ignored. Unfortunately, the data for 2021 was missing or largely incomplete for every NOAA station within 20 miles of Dauphin Island, so we had to use data from an offshore station about 30 ESE of the other Dauphin Island stations. This data may be different than what was actually observed at Dauphin Island, so it is important to note that our results may be influenced. We would much prefer statistics from Dauphin Island itself in the year 2021, so our data analysis can be rerun if it is ever uncovered.

It may also be useful to our analysis finding exact data on electricity output and usage over the last decade or more in Alabama. For the purposes of this paper, we did not find it to be necessary that we use exact data. Instead, we cited data from the United States Energy Information Administration and the World Nuclear Association to make claims and analyses.

## Local and Global Perspectives
We can connect the data we have collected to previous studies to help build a better understanding of water temperature in cooling nuclear reactors. In an article about Climate Resilience, Matthew Bandyk states the Oyster Creek nuclear power plant was closed, "rather than spend \$800 million developing a new water cooing system in order to reduce the amount of heated water the plant discharged into the local bay. . . harming the aquatic ecosystem" [@Bandyk2020]. If water temperatures become too consistently high, it is possible the Dauphin Island plant may have a future similar to the Oyster Creek plant. The article does not just focus on one power plant, though. They found there to be 17 cases in which a nuclear power plant in the United States had to reduce operations due to high water temperature in 2019. That number increased to 25 cases in 2020. Bandyk mentions though, that the trend is not linear, and can fluctuate based on yearly weather patterns like El Nino. This data signals shutdowns due to extreme heat are not as rare as they may initially seem.

This use of water to cool nuclear power plants is not just exclusive to Dauphin Island, Alabama, or even the United States. Worldwide, this same system is used. Different countries or regions may have different guidelines on ideal water temperature, but the idea and consequences are the same. For example, the World Nuclear Association writes about the Brown's Ferry Nuclear Power Plant in Northern Alabama, "In mid 2010, TVA had to reduce power at its three Brown's Ferry Units in Alabama to 50% in order to keep river water temperatures below 32°C, at a cost to some \$50 million to customers" [@Cooling2020]. Worldwide, almost 10% of all energy used comes from the 440 nuclear power plants across the globe [@WNA2025]. The World Nuclear Association states that some countries like France, Hungary, or Ukraine, rely on nuclear energy for more than half of their electricity. In these cases, the threat of operating at half capacity is more daunting, as it can effect much of a country's power output.

## Future Assessment
Despite the research we have done on the topic, there are multiple opportunities to build on the knowledge gained. Using local and national guidelines, one can research the probability of partial shutdowns at any nuclear power plant across the world. It may be particularly helpful to research France's nuclear power plants as they supply over 70% of the country's electrical output. A major heat wave and increase in surrounding water temperatures could lead to ruinous power outages across the country. Researching the probability of these outages and the effects they could have is a great first step to mitigating a country-wide disaster.

Due to increasing concern for the effects of climate change on environments, we would also recommend further research be done on how the Dauphin Island power plant may be effected. If water temperature is increasing on average year-over-year, the power plant could be at risk for longer periods of working at 50% capacity, further straining power supplies in Alabama. Prevention and alleviation tactics would be the best focuses of future study. In addition, alternative water sources or water cooling systems could help ease the stress on nuclear power plants. The use of groundwater is an intriguing topic, but its slow replenishment could lead to future resource issues. Rapid cooling of sea water is another interesting idea, but trade offs must be studied to find the feasibility of this idea. Upgrading existing cooling features like building a secondary cooling tower to make the process more efficient should be looked into as well.
