---
title: "Draft: Data Documentation"
editor: 
  markdown: 
    wrap: 72
---

### Source 1

#https://www.ncei.noaa.gov/access/coastal-water-temperature-guide/all_table.html#
This gives average monthly temperature of the water off Dauphin island.
There are *Information Quality* and *Disclaimer* tabs at the bottom of
the page, although the *Disclaimer* tab doesn't say anything of
importance. Information Quality says that the data has to follow
guidelines from a Treasury and General Government Appropriations act for
fair and accurate reporting. The data would be used to evaluate the
likelihood of water temps reaching the 85 degree threshold in different
months. Unfortunately, it doesn't have daily data, so we'd look
elsewhere for that. [@nceicoa]

#read fwf to fix the data we read in#
https://www.ndbc.noaa.gov/obs.shtml Click on link to get to map. Click
on view history. Then can download any data wanted dpha12024.txt. This
site has real data every half hour for all of 2024 that comes directly
from the Dauphin Island site. There's also data from 2021-2023, and from
January of 2025. I would want to use this data like I said above,
finding the likelihood of water temps reaching 85 degrees (or 29.444
degrees Celcius). @nceicoa

```{R}
setwd("C:/Users/Dominic Sander/Downloads/Stat 349")
library(readr)
dpha2h2012 <- read_table("dpha1h2012.txt")
dpha2h2013 <- read_table("dpah1h2013.txt")
dpha2h2014 <- read_table("dpha1h2014.txt")
dpha2h2015 <- read_table("dpha1h2105.txt")
dpha2h2016 <- read_table("dpha2h2016.txt")
dpha2h2017 <- read_table("dpha2h2017.txt")
dpha2h2018 <- read_table("dpha2h2018.txt")
dpha2h2019 <- read_table("dpha2h2019.txt")
dpha2h2020 <- read_table("dpha2h2020.txt")
X42012h2021 <- read_table("42012h2021.txt")
dpha2h2022 <- read_table("dpha2h2022.txt")
dpha2h2023 <- read_table("dpha2h2023.txt")
dpha2h2024 <- read_table("dpha2h2024.txt")


```


```{R setup}
library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)

dpha2_12 <- dpha2h2012 %>% select("#YY","MM","DD","hh","mm","OTMP") %>%
   rename(WTMP=OTMP)
dpha2_12 <- dpha2_12[-1, ]

dpha2_13 <- dpha2h2013 %>% select("#YY","MM","DD","hh","mm","OTMP") %>%
   rename(WTMP=OTMP)
dpha2_13 <- dpha2_13[-1, ]

dpha2_14 <- dpha2h2014 %>% select("#YY","MM","DD","hh","mm","OTMP") %>%
   rename(WTMP=OTMP)
dpha2_14 <- dpha2_14[-1, ]

dpha2_15 <- dpha2h2015 %>% select("#YY","MM","DD","hh","mm","OTMP") %>%
   rename(WTMP=OTMP)
dpha2_15 <- dpha2_15[-1, ]

dpha2_16 <- dpha2h2016 %>% select("#YY","MM","DD","hh","mm","OTMP") %>%
   rename(WTMP=OTMP)
dpha2_16 <- dpha2_16[-1, ] 

dpha2_17 <- dpha2h2017 %>% select("#YY","MM","DD","hh","mm","OTMP") %>%
  rename(WTMP=OTMP)
dpha2_17 <- dpha2_17[-1, ]

dpha2_18 <- dpha2h2018 %>% select("#YY","MM","DD","hh","mm","OTMP") %>%
  rename(WTMP=OTMP)
dpha2_18 <- dpha2_18[-1, ]

dpha2_19 <- dpha2h2019 %>% select("#YY","MM","DD","hh","mm","OTMP") %>%
  rename(WTMP=OTMP)
dpha2_19 <- dpha2_19[-1, ]

dpha2_20 <- dpha2h2020 %>% select("#YY","MM","DD","hh","mm","OTMP") %>%
  rename(WTMP=OTMP)
dpha2_20 <- dpha2_20[-1, ]

X42012h_21 <- X42012h2021 %>% select("#YY","MM","DD","hh","mm","WTMP")
X42012h_21 <- X42012h_21[-1, ]

dpha2_22 <- dpha2h2022 %>% select("#YY","MM","DD","hh","mm","WTMP") 
dpha2_22 <- dpha2_22[-1, ]
dpha2_23 <- dpha2h2023 %>% select("#YY","MM","DD","hh","mm","WTMP") 
dpha2_23 <- dpha2_23[-1, ]
dpha2_24 <- dpha2h2024 %>% select("#YY","MM","DD","hh","mm","WTMP") 
dpha2_24 <- dpha2_24[-1, ]

dpha_combined <- bind_rows(dpha2_12, dpha2_13, dpha2_14, dpha2_15, dpha2_16, dpha2_17, dpha2_18, dpha2_19, dpha2_20, X42012h_21, dpha2_22, dpha2_23, dpha2_24
) %>%
  arrange(`#YY`, MM, DD, hh, mm) %>%
  filter(WTMP <=40)

```

Create dataset for av temp
```{R}
dpha_av <- dpha_combined %>%
  mutate(WTMP = as.numeric(WTMP)) %>%
  filter(WTMP <=40) %>%
  group_by('#YY', MM, DD) %>%
  summarize(Avg_WTMP = mean(WTMP, na.rm = TRUE), .groups = "drop")

dpha_over85 <- dpha_av %>%
  filter(Avg_WTMP>=29.4444)

```

Graph of av. temp by day
```{R}
colnames(dpha_av)
dpha_av <- dpha_av %>%
  select(-`\"#YY\"`)

ggplot(dpha_av, aes(x = factor(paste(MM, DD, sep = "-")), y = Avg_WTMP)) +
  geom_bar(stat = "identity", fill = "deepskyblue4") + 
  geom_hline(yintercept = 29.44, linetype = "dashed", color = "red") +
  labs(x = "Day", y = "Av. Water Temp °C", title = "Daily Av. Water Temp 2012-2024") +
  theme(axis.text.x = element_blank(),  
        axis.ticks.x = element_blank(), 
        plot.title = element_text(hjust = 0.5))

```

Total Days Per Month With Av. Over 29.44
```{R}

month_count <- dpha_over85 %>%
  group_by(MM) %>%
  summarize(Count=n(), .groups="drop")%>%
  complete(MM=sprintf("%02d", 1:12), fill = list(Count=0))

data(month_count)
kable(month_count)

```

Total Days Per Month With Obs. > 29.44 in 2024
```{R}
dpha2_24_29 <- dpha2_24 %>%
  filter(WTMP >= 29.44) %>%
  filter(WTMP <= 50)

month_obs <- dpha2_24_29 %>%
  group_by(MM) %>%
  summarize(Days = n_distinct(DD), .groups = "drop")

kable(month_obs, caption="Total Days Per Month With an Obs. > 29.44° C", col.names=c("Month", "Total Days"))
```

Total days per year with daily max temp above 29.44
```{R}
library(lubridate)
dpha_combined <- dpha_combined %>%
  mutate(
    Date = make_date(year = as.integer(`#YY`), month = as.integer(MM), day = as.integer(DD))
  )

year_above_29 <- dpha_combined %>%
  filter(WTMP >= 29.44, WTMP <= 50) %>%
  group_by(Year = year(Date)) %>%
  summarise(
    Days_Above_29_44C = n_distinct(Date), 
    Max_temp = max(WTMP, na.rm=TRUE),
    .groups = "drop",
    )
```


Predictive model for next five years
```{R}
water_model <- lm(Days_Above_29_44C ~ Year, data = year_above_29)

summary(water_model)  


future_data <- data.frame(Year = seq(max(year_above_29$Year) + 1, by = 1, length.out = 5))

# Predict with confidence intervals
future_predictions <- predict(water_model, newdata = future_data, interval = "prediction")

# Combine predictions with years
forecast <- cbind(future_data, round(as.data.frame(future_predictions), 1))
names(forecast) <- c("Year", "Predicted_Hot_Days", "Lower", "Upper")

print(forecast)
```

Graphs for predictions - 
```{R}
year_above_29 <- year_above_29 %>%
  mutate(
    Max_temp = as.numeric(Max_temp),
    Days_Above_29_44C = as.numeric(Days_Above_29_44C)
  )

# Simple plot
ggplot(year_above_29, aes(x = Year)) +
  geom_bar(aes(y = Days_Above_29_44C), stat = "identity", fill = "deepskyblue4") 
  
```

Max temp per year
```{R}
water_model_max <- lm(Max_temp ~ Year, data = year_above_29)

summary(water_model_max)  


future_data_max <- data.frame(Year = seq(max(year_above_29$Year) + 1, by = 1, length.out = 5))

# Predict with confidence intervals
future_predictions_max <- predict(water_model_max, newdata = future_data_max, interval = "prediction")

# Combine predictions with years
forecast_max <- cbind(future_data_max, round(as.data.frame(future_predictions_max), 1))
names(forecast_max) <- c("Year", "Predicted Highest Temp", "Lower", "Upper")

print(forecast_max)
```

Graph of max temp per year
```{R}
ggplot(year_above_29, aes(x=Year, y=Max_temp)) +
  geom_line() +
  geom_point(color = "deepskyblue4") +
  labs(x = "Year", y = "Max. Water Temp °C", title = "Max. Yearly Water Temp 2012-2024") 
  
```



#https://www.sciencedirect.com/science/article/pii/S2211467X24000725
This is an article about the dangers of climate change on nuclear
reactors, specifically in the United States. It describes how nuclear
reactors use water to cool themselves down, and if the water temperature
is too high, reactors will have to operate at a lower capacity. It also
shows energy usage in different continents, impacts of lower nuclear
output, and measures to respond for future risks. @portugal-pereira2024

#https://www.eia.gov/electricity/data/browser/ Has data on electricity
usage, nuclear power output, and state-by-state breakdowns of important
power information. This data can help us determine how heavily a shut
down of the reactor would impact Alabama. @electric

#https://world-nuclear.org/information-library/current-and-future-generation/cooling-power-plants
Talks about a couple of specific instances where water got too hot and
the plant had to operate on reduced power. The amount of money it cost
consumers is recorded as well as the temperature threshold. There are a
couple of examples and all of them have different limits to how hot the
water can be around their plant. @cooling
