# Introduction

There are many well-known risks involved with nuclear power generation, one of those being overheating of the cooling system. In many plants, water is used to cool the reactor and transfer thermal heat that can be transformed into electricity. This is crucial in a nuclear power plant, but if that water is too hot initially, the plant cannot run efficiently and may damage the surrounding environment. This is what we are trying to study at the Dauphin Island Nuclear Power Plant on Dauphin Island in Alabama. What is the risk of the "cooling water" getting too hot for the plant to operate at full capacity?

Multiple studies have found increased water temperature to be detrimental to the operation of a nuclear power plants across the world. The World Nuclear Organization details multiple accounts of this happening in their article on cooling power plants. They say, ". . . had to reduce power at its three Browns Ferry units in Alabama to 50% in order to keep river water temperatures below 32 degrees Celsius. . . Rhine and Neckar River temperatures . . . approached the critical 28 degrees Celsius, and nuclear and coal-fired plants were threatened with closure. In August of 2012 one unit of Millstone power station in Connecticut was closed because the seawater in Long Island Sound exceeded 24 degrees Celsius" [@Cooling2020]. This gives us a good idea of what is to be expected when water temperatures get too high. However, we want to know about the Dauphin Island plant off the southern coast of Alabama. There is little to no information about nuclear power stations in the area that use seawater to cool the reactors, so we hope to fill in that gap and find the risk of a partial shutdown.

Using data from weather stations in the area, we analyzed the probability of the Dauphin Island plant having to reduce their operations due to increased cooling water. Our findings indicated most summer days reach a temperature above the guideline, forcing our plant to reduce operations to half . 95 percent confidence intervals suggest there will be a minimum of 30 days worth of shutdowns each of the next five years, with the potential for up to 170 days. We also found nuclear power to be a large source of power in Alabama, leading to potential power outages if the plant were to be forced to function at 50% output.

#This is a book created from markdown and executable code. #See @knuth84 for additional discussion of literate programming. - Can I delete these?
